### ISSUE TITLE
properties are ignored on create/update

### ISSUE THREAD

**Issue by hardys** [openshift-metalkube/terraform-provider-ironic#8]
Currently we put root_device in instance_info, which doesn't work as it needs to be specified in the properties.

Fixing that in dev-scripts I noticed that actually we ignore properties in the schema conversion on create, and also on update

We'll need to fix that, and in particular it makes deploying on boxes with multiple disks break as we can't specify the root disk anymore.

**Comment by hardys** [comment]
I've taken this as started working on a fix

**Comment by hardys** [comment]
Ok discussed this with @stbenjam and it's more complex than I thought, because the terraform schema is static, and somewhere under the hood it's expecting a map of strings.

Unless we can resolve that (and it sounds like it may not be fully fixed until we move to the terraform 0.12 branch that's not yet released), it seems like we may need to modify gophercloud to optionally deserialized a json string, and pass the resulting map to Ironic.

**Comment by stbenjam** [comment]
I don't think gophercloud would accept a PR to accommodate a limitation from terraform.  We'll probably have to handle it here.

We could change `properties` to TypeString, and marshal/unmarshal it before sending to gophercloud.  Untested by something like this - https://github.com/openshift-metalkube/terraform-provider-ironic/commit/2ade41cd253cc74aa0a05c5c19212a093e0a6dc2
https://github.com/openshift-metalkube/terraform-provider-ironic/commit/55c8a20274a21714ec9cf713019ad4c7130b20ac

It's not great, I'll have to think about it some more...
